# 本番用ではなく，デバッグ用
include:
  - path: ./server/compose.yml
services:
  frontend:
    image: node:23
    build: 
      context: ./frontend
      target: dev
    ports: 
      - "5173:5173"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules

