# 本番用ではなく，デバッグ用
services:
  frontend:
    image: node:23
    build: 
      context: ./frontend
      target: dev
    ports: 
      - "5173:5173"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules

